update_frequency_milliseconds: 100
elements_per_update: 50

max_price: 10000

symbols:
    - zbU
    - Ucd
    - pgW
    - ATz
    - NkD
    - Res
    - PiK
    - hQi
    - TnD
    - rQl
    - BHz
    - bmA
    - dFm
    - Zve
    - LyH
    - PGM
    - Wyu
    - hEY
    - PbF
    - NVe
    - SLx
    - tRu
    - MbM
    - kgo
    - MoE
    - wWg
    - vee
    - Hjz
    - AoL
    - THj
    - gdC
    - PGB
    - IjC
    - hlq
    - EoS
    - HdA
    - Qmd
    - nNm
    - Tbr
    - ZmD
    - KgJ
    - NHx
    - QMS
    - wyu
    - yUb
    - YtF
    - XjK
    - zaD
    - xWY
    - UHa
    - tXz
    - kco
    - Mct
    - YZl
    - DkT
    - Jbi
    - XDX
    - OKS
    - gph
    - rTS
    - Khz
    - Gso
    - xNr
    - ZWl
    - AaV
    - ngs
    - kIP
    - uHX
    - bOp
    - mWu
    - tjq
    - trH
    - gcN
    - Sfl
    - pZs
    - DVM
    - ZgK
    - Fga
    - DsS
    - OIb
    - OLj
    - ggN
    - GBS
    - alZ
    - CWd
    - gDc
    - pek
    - CJX
    - Orq
    - HYa
    - ZSe
    - sOA
    - tUp
    - FgU
    - Psw
    - WbS
    - czf
    - OsN
    - hcb
    - DcY
    - lys
    - UhY
    - YVO
    - fft
    - wny
    - BxY
    - JsD
    - GTA
    - mDw
    - tkq
    - UMe
    - Dhf
    - VTV
    - IdF
    - iuJ
    - cdI
    - zxA
    - sjk
    - gbo
    - nqM
    - UbD
    - fQm
    - xIW
    - YwJ
    - UJk
    - yVe
    - qRj
    - vFP
    - QnC
    - pui
    - ewr
    - WTf
    - DvS
    - xzy
    - aSV
    - pHH
    - aqU
    - AMQ
    - YOY
    - isf
    - Vtu
    - DSI
    - VSM
    - afE
    - KJR
    - Mxj
    - fth
    - Jvr
    - LrG
    - XSP
    - LIs
    - iVq
    - NKu
    - LBS
    - CGk
    - rGv
    - uIH
    - VKC
    - cwM
    - wSw
    - NjD
    - QTt
    - Czr
    - Idp
    - MIH
    - lSH
    - Nvu
    - Brk
    - KeP
    - WgZ
    - NEj
    - MOa
    - EUX
    - dOm
    - yVG
    - rsa
    - WuX
    - OKH
    - Qcr
    - mgk
    - CCX
    - Gmn
    - etm
    - bVc
    - svD
    - LMn
    - qhE
    - Gjv
    - wfF
    - arV
    - OhR
    - AKf
    - TLo
    - QlO
    - hjg
    - XJp
    - Phg
    - Eed
    - dMW
    - kjJ
    - YKR
    - JZO
    - viE
    - qlG
    - xQV
    - CSk
    - zWi
    - Ybj
    - GGq
    - WYS
    - hiy
    - wNA
    - nGq
    - Prp
    - kSv
    - WvV
    - XLD
    - qOU
    - uyn
    - SNj
    - TlS
    - Piw
    - MLy
    - Teh
    - XaJ
    - kYQ
    - SDe
    - reP
    - MIR
    - YOf
    - Mmg
    - EYc
    - gDo
    - YNE
    - Qnj
    - OIR
    - aFJ
    - pvO
    - ijn
    - TvF
    - KtT
    - Yth
    - fIh
    - vRi
    - Knn
    - oOU
    - oZT
    - PVa
    - nLV
    - RSr
    - STE
    - aYu
    - yOK
    - lup
    - qik
    - NIt
    - TRZ
    - OyC
    - mwF
    - OLn
    - uXs
    - uAQ
    - eDI
    - Paf
    - frp
    - pEs
    - hdm
    - uiB
    - sUg
    - OUK
    - ogw
    - fEz
    - nBc
    - tJy
    - lhd
    - KAE
    - Jpb
    - GbM
    - zwq
    - vEX
    - mZQ
    - fpj
    - UyQ
    - vIX
    - Kak
    - IKL
    - QJr
    - cCa
    - NBR
    - phD
    - iKp
    - GRx
    - cBv
    - PeB
    - SDC
    - MsX
    - Ltg
    - xhF
    - biE
    - RKz
    - UgK
    - Hih
    - RWD
    - onm
    - Pqe
    - MeR
    - Itq
    - Lwp
    - diB
    - hfo
    - OZR
    - rZX
    - pfz
    - YMf
    - CQV
    - pjv
    - xFv
    - Rbu
    - JKH
    - fdM
    - oda
    - sIy
    - BxK
    - flz
    - lrK
    - nkp
    - Qrq
    - IGB
    - OoS
    - Xpu
    - ScR
    - hQv
    - duo
    - Fkp
    - TcJ
    - fvu
    - VQL
    - qym
    - ZlZ
    - KRS
    - FqV
    - UtJ
    - XkN
    - YoO
    - bCs
    - nzM
    - XQj
    - lfb
    - NmH
    - UQx
    - LRj
    - vwh
    - RaH
    - WLw
    - BSf
    - NVm
    - wdc
    - mOv
    - cer
    - DGA
    - YRh
    - fUm
    - YCc
    - hTV
    - EdN
    - bRn
    - kAg
    - nfk
    - FVz
    - XCj
    - wkc
    - QTr
    - fTU
    - lKP
    - bPo
    - XAK
    - Xol
    - PfQ
    - emD
    - gvh
    - dah
    - pmA
    - Tsx
    - wdJ
    - PWC
    - Tqf
    - tNJ
    - bYT
    - Toj
    - MEp
    - JMW
    - nHU
    - zCX
    - Swm
    - vsE
    - EPC
    - iFV
    - UZF
    - ccs
    - aGB
    - Zpt
    - DLM
    - Hta
    - YQq
    - KxW
    - Hmi
    - YGL
    - loZ
    - oig
    - ULy
    - Alr
    - NpP
    - XXT
    - TvD
    - VKG
    - INn
    - OAr
    - sUg
    - AaP
    - FJo
    - iPA
    - Kfd
    - huo
    - pjt
    - qcN
    - YrV
    - idN
    - Ysi
    - pke
    - Mwq
    - ueg
    - drr
    - ZxE
    - LJu
    - PZg
    - wPv
    - EkY
    - UjZ
    - QmQ
    - wBx
    - EaY
    - ONv
    - cLv
    - HRh
    - qal
    - mjc
    - jyS
    - DwD
    - sXn
    - sfg
    - UGL
    - ErF
    - HNn
    - bhC
    - rmy
    - xhw
    - WHT
    - Qmp
    - rzE
    - IoB
    - uKU
    - IYo
    - JGl
    - jPl
    - Eho
    - zNh
    - anm
    - OAj
    - NqM
    - uwH
    - dMT
    - AMq
    - dAp
    - iJl
    - EAZ
    - iOu
    - LAn
    - tnr
    - rtV
    - gUL
    - NwR
    - kFI
    - HGR
    - msM
    - ZaO
    - bHh
    - xgR
    - njN
    - EOb
    - Zgt
    - ASc
    - nFm
    - hBC
    - RLO
    - xQN
    - ceV
    - fUs
    - Beu
    - wbS
    - QAJ
    - JzU
    - LuG
    - mWE
    - EjR
    - PkD
    - gLz
    - niS
    - Wnt
    - AIX
    - adF
    - Glz
    - nAF
    - Ihk
    - YKO
    - UeW
    - kKn
    - DlL
    - YuV
    - HZK
    - xol
    - ZAn
    - mDA
    - Seo
    - HSl
    - hpX
    - yQx
    - OWS
    - qyG
    - TYd
    - ZTa
    - DHb
    - luT
    - Hwr
    - ihD
    - Oij
    - yjI
    - Xdq
    - JBl
    - LDe
    - Saz
    - Dcv
    - Ivy
    - Zxy
    - tBz
    - Urn
    - dJW
    - WiS
    - rxV
    - fmt
    - yND
    - nSD
    - XGV
    - dBd
    - xef
    - Uyq
    - yQL
    - JiD
    - oJr
    - OnS
    - eJl
    - atS
    - DfO
    - VZB
    - PbK
    - tPr
    - foj
    - KUm
    - kqv
    - Bru
    - Ndq
    - Rqn
    - egJ
    - idE
    - hMs
    - Aca
    - NLu
    - IFU
    - FWY
    - XXq
    - meI
    - UhO
    - cVr
    - Gsr
    - tke
    - KDH
    - jMs
    - qZu
    - gkn
    - xWE
    - ZLN
    - bnf
    - uGe
    - hOe
    - ZPV
    - QWC
    - isA
    - SkV
    - dBo
    - PHr
    - yGg
    - FHo
    - ELg
    - Ypm
    - zNy
    - ZZD
    - zsC
    - Tfw
    - Hkh
    - Qgr
    - YOi
    - SFE
    - oMG
    - hmC